// Code generated by go-bindata.
// sources:
// nginx/nginx.conf
// nginx/spacer/log.lua
// nginx/spacer/run.lua
// nginx/spacer/service.lua
// nginx/spacer/trace.lua
// spacer.example.yml
// DO NOT EDIT!

package spacer

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// nginxNginxConf reads file data from disk. It returns an error on failure.
func nginxNginxConf() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/nginx/nginx.conf"
	name := "nginx/nginx.conf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// nginxSpacerLogLua reads file data from disk. It returns an error on failure.
func nginxSpacerLogLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/nginx/spacer/log.lua"
	name := "nginx/spacer/log.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// nginxSpacerRunLua reads file data from disk. It returns an error on failure.
func nginxSpacerRunLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/nginx/spacer/run.lua"
	name := "nginx/spacer/run.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// nginxSpacerServiceLua reads file data from disk. It returns an error on failure.
func nginxSpacerServiceLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/nginx/spacer/service.lua"
	name := "nginx/spacer/service.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// nginxSpacerTraceLua reads file data from disk. It returns an error on failure.
func nginxSpacerTraceLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/nginx/spacer/trace.lua"
	name := "nginx/spacer/trace.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// spacerExampleYml reads file data from disk. It returns an error on failure.
func spacerExampleYml() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/spacer.example.yml"
	name := "spacer.example.yml"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"nginx/nginx.conf": nginxNginxConf,
	"nginx/spacer/log.lua": nginxSpacerLogLua,
	"nginx/spacer/run.lua": nginxSpacerRunLua,
	"nginx/spacer/service.lua": nginxSpacerServiceLua,
	"nginx/spacer/trace.lua": nginxSpacerTraceLua,
	"spacer.example.yml": spacerExampleYml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"nginx": &bintree{nil, map[string]*bintree{
		"nginx.conf": &bintree{nginxNginxConf, map[string]*bintree{}},
		"spacer": &bintree{nil, map[string]*bintree{
			"log.lua": &bintree{nginxSpacerLogLua, map[string]*bintree{}},
			"run.lua": &bintree{nginxSpacerRunLua, map[string]*bintree{}},
			"service.lua": &bintree{nginxSpacerServiceLua, map[string]*bintree{}},
			"trace.lua": &bintree{nginxSpacerTraceLua, map[string]*bintree{}},
		}},
	}},
	"spacer.example.yml": &bintree{spacerExampleYml, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

