// Code generated by go-bindata.
// sources:
// lib/internal_token.lua
// lib/router.lua
// lib/run.lua
// lib/service.lua
// lib/topics.lua
// lib/trace.lua
// lib/uuid.lua
// app/gateway.lua
// app/hello.lua
// app/lib/foo.lua
// bin/start-production.sh
// bin/start.sh
// bin/test.sh
// appignore
// hello.t.md
// DO NOT EDIT!

package spacer

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// libInternal_tokenLua reads file data from disk. It returns an error on failure.
func libInternal_tokenLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/lib/internal_token.lua"
	name := "lib/internal_token.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libRouterLua reads file data from disk. It returns an error on failure.
func libRouterLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/lib/router.lua"
	name := "lib/router.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libRunLua reads file data from disk. It returns an error on failure.
func libRunLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/lib/run.lua"
	name := "lib/run.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libServiceLua reads file data from disk. It returns an error on failure.
func libServiceLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/lib/service.lua"
	name := "lib/service.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libTopicsLua reads file data from disk. It returns an error on failure.
func libTopicsLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/lib/topics.lua"
	name := "lib/topics.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libTraceLua reads file data from disk. It returns an error on failure.
func libTraceLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/lib/trace.lua"
	name := "lib/trace.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libUuidLua reads file data from disk. It returns an error on failure.
func libUuidLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/lib/uuid.lua"
	name := "lib/uuid.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// appGatewayLua reads file data from disk. It returns an error on failure.
func appGatewayLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/app/gateway.lua"
	name := "app/gateway.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// appHelloLua reads file data from disk. It returns an error on failure.
func appHelloLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/app/hello.lua"
	name := "app/hello.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// appLibFooLua reads file data from disk. It returns an error on failure.
func appLibFooLua() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/app/lib/foo.lua"
	name := "app/lib/foo.lua"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// binStartProductionSh reads file data from disk. It returns an error on failure.
func binStartProductionSh() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/bin/start-production.sh"
	name := "bin/start-production.sh"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// binStartSh reads file data from disk. It returns an error on failure.
func binStartSh() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/bin/start.sh"
	name := "bin/start.sh"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// binTestSh reads file data from disk. It returns an error on failure.
func binTestSh() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/bin/test.sh"
	name := "bin/test.sh"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// appignore reads file data from disk. It returns an error on failure.
func appignore() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/appignore"
	name := "appignore"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// helloTMd reads file data from disk. It returns an error on failure.
func helloTMd() (*asset, error) {
	path := "/Users/poga/projects/go/src/github.com/poga/spacer/hello.t.md"
	name := "hello.t.md"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"lib/internal_token.lua": libInternal_tokenLua,
	"lib/router.lua": libRouterLua,
	"lib/run.lua": libRunLua,
	"lib/service.lua": libServiceLua,
	"lib/topics.lua": libTopicsLua,
	"lib/trace.lua": libTraceLua,
	"lib/uuid.lua": libUuidLua,
	"app/gateway.lua": appGatewayLua,
	"app/hello.lua": appHelloLua,
	"app/lib/foo.lua": appLibFooLua,
	"bin/start-production.sh": binStartProductionSh,
	"bin/start.sh": binStartSh,
	"bin/test.sh": binTestSh,
	"appignore": appignore,
	"hello.t.md": helloTMd,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"app": &bintree{nil, map[string]*bintree{
		"gateway.lua": &bintree{appGatewayLua, map[string]*bintree{}},
		"hello.lua": &bintree{appHelloLua, map[string]*bintree{}},
		"lib": &bintree{nil, map[string]*bintree{
			"foo.lua": &bintree{appLibFooLua, map[string]*bintree{}},
		}},
	}},
	"appignore": &bintree{appignore, map[string]*bintree{}},
	"bin": &bintree{nil, map[string]*bintree{
		"start-production.sh": &bintree{binStartProductionSh, map[string]*bintree{}},
		"start.sh": &bintree{binStartSh, map[string]*bintree{}},
		"test.sh": &bintree{binTestSh, map[string]*bintree{}},
	}},
	"hello.t.md": &bintree{helloTMd, map[string]*bintree{}},
	"lib": &bintree{nil, map[string]*bintree{
		"internal_token.lua": &bintree{libInternal_tokenLua, map[string]*bintree{}},
		"router.lua": &bintree{libRouterLua, map[string]*bintree{}},
		"run.lua": &bintree{libRunLua, map[string]*bintree{}},
		"service.lua": &bintree{libServiceLua, map[string]*bintree{}},
		"topics.lua": &bintree{libTopicsLua, map[string]*bintree{}},
		"trace.lua": &bintree{libTraceLua, map[string]*bintree{}},
		"uuid.lua": &bintree{libUuidLua, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

